# user info
user:
  name: Acerkaio
  first_name: Theme
  last_name: Async
  email: 
  domain: 站点域名
  avatar: /img/avatar.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

# logo
favicon:
  logo: /img/favicon.svg
  icon16: /img/favicon.svg
  icon32: /img/favicon.svg
  appleTouchIcon: 
  webmanifest:
  visibilitychange: false
  hidden: /failure.ico # Displays an icon when not visible
  showText: favicon.showText
  hideText: favicon.hideText

# Theme resource files or plug-ins
assets:
  plugin:
    row:
      css: css/plugins/bootstrap.row.css
    swup:
      js: //cdn.jsdelivr.net/npm/swup@2.0.19/dist/swup.min.js
    locomotive_scroll:
      css: //cdn.jsdelivr.net/npm/locomotive-scroll@4.1.4/dist/locomotive-scroll.min.css
      js: //cdn.jsdelivr.net/npm/locomotive-scroll@4.1.4/dist/locomotive-scroll.min.js
    fancybox: 
      css: //cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
      js: //cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    typing:
      js: js/plugins/typing.js
    search:
      js: [//cdn.jsdelivr.net/npm/hexo-generator-searchdb@1.4.0/dist/search.js, js/plugins/local_search.js]
    swiper: 
      css: //cdn.jsdelivr.net/npm/swiper@4.5.1/dist/css/swiper.min.css
      js: //cdn.jsdelivr.net/npm/swiper@4.5.1/dist/js/swiper.min.js
    katex:
      js: //cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js
      css: //cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
      auto_render: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js
      copy_tex:
        css: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.css
        js: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
  icons: 
    type: font # font symbol
    css:  css/plugins/font-awesome.min.css
    js:

# cdn
cdn:
  css: 
  js:
    head:
    base: 
    async: 
    defer: 

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd

# Top navigation menu
top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/

# Banner settings
banner:
  default:
    type: img
    bgurl: /img/banner.png
    bannerText: Hi my new friend!
  index:
    type: video
    bgurl: /img/晚上.mp4
    bannerTitle: 深山踏红叶，<br>耳畔闻鹿鸣。
    bannerText: Hi my new friend!
    videoUrl: 
  archive:
    type: img
    bgurl: /img/mountain.jpg
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    type: img
    bgurl: /img/sky.jpg
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    type: img
    bgurl: /img/darkwaterskysunlightreflectionnatureoutdoorslandscapelake.jpg
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me

# Sidebar settings
sidebar:
  typedTextPrefix: I`m
  typedText: [ 'OIer' ]
  info: 
    - key: sidebar.residence
      val: Earth
    - key: sidebar.city
      val: Ganzhou
    - key: sidebar.age
      val: 13
  social:
    - name: Github
      icon: fab fa-github
      url: https://github.com/acerkaio
    - name: Luogu
      icon: fas fa-code
      url: https://www.luogu.com.cn/user/514850

# About page settings
about:
  title: 如果一切都是镜花水月，那就让这万物走向终结。如果一切皆是命中注定，那就让这世界消失殆尽。
  introduction: 注定地，我是 <strong>Acerkaio</strong>，相遇即是缘分，很感谢您能够饶有兴致地浏览这个页面。作为一名 OIer，我将分享：题目题解、生活日常、和一些有趣的东西。
  blog: 
    <ul class="trm-list">
      <li>作者：Acerkaio </li>
      <li>主题：Hexo-theme-async </li>
    </ul>
  privacy: 
    本网站不会追踪访客行为，且不要求访客提供任何敏感信息（比如真实姓名、身份证号码、手机号等），因而也不存在任何隐私泄漏问题。访客参与评论，必须遵守法律法规和基本道德规范，文明礼貌。严禁发布任何有关淫秽、反动、暴力、博彩、恐吓、低俗的内容或违法信息，在尊重言论自由的同时请保持和平与理性。请勿对他人采取不友好的评论或其它过激行为。

# Footer settings
footer:
  # Hexo link (Powered by Hexo).
  powered:
    enable: false
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    icp: 
  # Copyright date
  copyrightYear:
  # 
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 08/30/2022 15:00:00
  #
  custom_text: <strong>QAQ</strong>

# archive
archive:
  type: more # less more

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: true
  comment: reward.comment
  # url:
  methods:
    - name: 支付宝
      path: https://pic1.imgdb.cn/item/6338329b16f2c2beb1ed61a4.jpg

# img loading="lazy"
lazyload:
  enable: true

# Page Visit Statistics
webAnalytics:  
  enable: false 
  baidu:   # Baidu key
  google:  # Tracking ID for Google statistics
  tencent: # Tencent statistics
    sid:
    cid:

# comment
comment:
  enable: false
  bComments:
    v: 0.0.12
    env: 

# Theme mode 
theme: 
  switch: true 
  default: auto # style-light style-dark

# Service Worker
sw: false

# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: false
  count: true
  time: true

# That is it only render those page which has `katex: true` in Front-matter.
# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: false
  # Options are for katex rendering options: https://katex.org/docs/options.html
  # In page katex options are also possible and will be merged
  options: {}

# Blog search
search:
  enable: false
  type: engine #local engine
  href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled
swup: false
